app:
  # ボットトークン
  # discord developer portalで取得したトークンを設定します
  # トークンが漏洩すると、ボットが第三者に悪用される恐れがあります
  # 外部には絶対に公開しないでください
  token: "#### replace with your token! ####"

  # コマンドプレフィックス
  # ボットがコマンドを識別するための記号を設定します
  # サーバー内でボットを複数使用する場合や、他のボットとコマンドが
  # 競合する場合に変更してください
  cmd_prefix: "."

  # 声質
  # ボットのデフォルトの声質を設定します
  # 以下のいずれかから選択できます
  # n  : nitech_jp_atr503_m001.htsvoice
  # ma : mei_angry.htsvoice
  # mb : mei_bashful.htsvoice
  # mh : mei_happy.htsvoice
  # mn : mei_normal.htsvoice
  # ms : mei_sad.htsvoice
  # ta : takumi_angry.htsvoice
  # th : takumi_happy.htsvoice
  # tn : takumi_normal.htsvoice
  # ts : takumi_sad.htsvoice
  voice_type: "n"

# ログ出力設定
# これ以降は、コンソール画面やログファイルに出力するログ設定です
# バグ調査の際に変更することがありますが、通常利用では変更の必要はありません
version: 1
formatters:
  console:
    format: '%(asctime)s - %(levelname)7s - %(name)10s - %(message)s'
    datefmt: '%H:%M:%S'
  file:
    format: '%(asctime)s - %(levelname)7s - %(name)15s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    maxBytes: 1000000
    backupCount: 3
    filename: yomiage.log
    formatter: file
loggers:
  root:
    level: WARN
    handlers: [console]
  yomiage:
    level: INFO
disable_existing_loggers: False